title:  Bethany Dearlove
tagline:  computational biologist
author:
  name: Bethany Dearlove
  twitter:  bethanydearlove

#google-ID: 'UA-80213386-1'

menu:
- {name: 'Research', url: 'about.html'}
- {name: 'Blog', url: 'writing.html'}
- {name: 'CV', url: 'cv.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/bdearlove'}
- {icon: 'twitter', link: 'https://twitter.com/bethanydearlove'}



# Available social icons are powered by Font Awesome, so you can use any icon that they offer
